export const posts = [
  {
    id: 1,
    cover: "http://dummyimage.com/650x300.jpg/5fa2dd/ffffff",
    title: "consequat morbi a ipsum",
    content:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
    createdAt: "2020-05-22T08:48:38Z",
    first_name: "Dennet",
    last_name: "Cromack",
    avatar: "https://robohash.org/veritatisculpaest.bmp?size=50x50&set=set1",
    commentsCount: 23,
    reactionsCount: 29,
  },
  {
    id: 2,
    cover: "http://dummyimage.com/650x300.jpg/ff4444/ffffff",
    title: "cursus id turpis integer aliquet",
    content:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.",
    createdAt: "2020-08-25T00:59:49Z",
    first_name: "Sheeree",
    last_name: "Scrivinor",
    avatar: "https://robohash.org/facilisidipsum.bmp?size=50x50&set=set1",
    commentsCount: 17,
    reactionsCount: 41,
  },
  {
    id: 3,
    cover: "http://dummyimage.com/650x300.jpg/cc0000/ffffff",
    title: "erat id mauris vulputate",
    content:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
    createdAt: "2021-01-13T05:10:44Z",
    first_name: "Hilly",
    last_name: "Jepson",
    avatar: "https://robohash.org/voluptatemrerumquo.png?size=50x50&set=set1",
    commentsCount: 24,
    reactionsCount: 52,
  },
  {
    id: 4,
    cover: "http://dummyimage.com/650x300.jpg/ff4444/ffffff",
    title: "rhoncus sed vestibulum sit amet cursus",
    content:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.",
    createdAt: "2020-09-22T15:18:55Z",
    first_name: "Tirrell",
    last_name: "Massingham",
    avatar: "https://robohash.org/etipsamsed.bmp?size=50x50&set=set1",
    commentsCount: 12,
    reactionsCount: 21,
  },
  {
    id: 5,
    cover: "http://dummyimage.com/650x300.jpg/cc0000/ffffff",
    title: "ut erat id mauris",
    content:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.",
    createdAt: "2020-08-27T11:24:34Z",
    first_name: "Orlando",
    last_name: "Kline",
    avatar: "https://robohash.org/fugaauthic.jpg?size=50x50&set=set1",
    commentsCount: 28,
    reactionsCount: 78,
  },
  {
    id: 6,
    cover: "http://dummyimage.com/650x300.jpg/ff4444/ffffff",
    title: "sem sed sagittis nam congue",
    content:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    createdAt: "2020-04-01T03:53:31Z",
    first_name: "Brennen",
    last_name: "Cowell",
    avatar: "https://robohash.org/utetad.bmp?size=50x50&set=set1",
    commentsCount: 26,
    reactionsCount: 80,
  },
  {
    id: 7,
    cover: "http://dummyimage.com/650x300.jpg/dddddd/000000",
    title: "quis orci nullam molestie",
    content:
      "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.",
    createdAt: "2020-06-05T07:58:49Z",
    first_name: "Jesselyn",
    last_name: "Dedam",
    avatar: "https://robohash.org/quiserrorvoluptates.bmp?size=50x50&set=set1",
    commentsCount: 42,
    reactionsCount: 11,
  },
  {
    id: 8,
    cover: "http://dummyimage.com/650x300.jpg/dddddd/000000",
    title: "primis in faucibus orci luctus",
    content: "Nulla mollis molestie lorem. Quisque ut erat.",
    createdAt: "2020-09-12T15:08:10Z",
    first_name: "Ernaline",
    last_name: "Salomon",
    avatar:
      "https://robohash.org/sapientequorepudiandae.png?size=50x50&set=set1",
    commentsCount: 12,
    reactionsCount: 44,
  },
  {
    id: 9,
    cover: "http://dummyimage.com/650x300.jpg/ff4444/ffffff",
    title: "vestibulum sit amet cursus id",
    content:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.",
    createdAt: "2020-08-31T00:50:48Z",
    first_name: "Felipa",
    last_name: "Bertomieu",
    avatar: "https://robohash.org/quorepellendusesse.bmp?size=50x50&set=set1",
    commentsCount: 36,
    reactionsCount: 23,
  },
  {
    id: 10,
    cover: "http://dummyimage.com/650x300.jpg/5fa2dd/ffffff",
    title: "dapibus nulla suscipit ligula",
    content: "Quisque porta volutpat erat.",
    createdAt: "2020-04-15T15:53:53Z",
    first_name: "Gennie",
    last_name: "Pardal",
    avatar: "https://robohash.org/occaecatiquonumquam.jpg?size=50x50&set=set1",
    commentsCount: 44,
    reactionsCount: 16,
  },
];
